from __future__ import division
import os
import time
import math
from glob import glob
import tensorflow as tf
import numpy as np
from six.moves import xrange

from ops import *
from utils import *

class DCGAN(object):
    def __init__(self, sess, input_size=28,
                 batch_size=100, sample_num=100, output_size=28,
                 z_dim=100, c_dim=1, dataset_name='default',
                 checkpoint_dir=None, sample_dir=None):
        """

        Args:
          sess: TensorFlow session
          input_size: The size of input image.
          batch_size: The size of batch. Should be specified before training.
          z_dim: (optional) Dimension of dim for Z. [100]
          c_dim: (optional) Dimension of image color. For grayscale input, set to 1. [1]
        """
        self.sess = sess

        self.batch_size = batch_size
        self.sample_num = sample_num

        self.input_size = input_size
        self.output_size = output_size

        self.z_dim = z_dim
        self.c_dim = c_dim

        self.dataset_name = dataset_name
        self.checkpoint_dir = checkpoint_dir

        self.build_model()

    def discriminator(self, image, reuse=False, train=True):
        with tf.variable_scope("discriminator", reuse=reuse):
            #######################################################
            # TODO: Define discrminator network structure here. op.py
            # includes some basic layer functions for you to use.
            # Please use batch normalization layer after conv layer.
            # And use 'train' argument to indicate the mode of bn.
            #######################################################

            h0 = lrelu(conv2d(image, self.c_dim, name='d_h0_conv'))

            h1 = lrelu(batch_norm(conv2d(h0, 64, name='d_h1_conv'), name='d_bn1'))
            h1 = tf.reshape(h1, [self.batch_size, -1])      
            
            h2 = lrelu(batch_norm(linear(h1, 1024, 'd_h2_lin'), name='d_bn2'))

            h3 = linear(h2, 1, 'd_h3_lin')
            
            return tf.nn.sigmoid(h3), h3
            #######################################################
            #                   end of your code
            #######################################################

    def generator(self, z, reuse=False, train=True):
        with tf.variable_scope("generator", reuse=reuse):
            #######################################################
            # TODO: Define decoder network structure here. The size
            # of output should match the size of images. Image scale
            # in DCGAN is [-1, +1], so you need to add a tanh layer
            # before the output. Also use batch normalization layer
            # after deconv layer, and use 'train' argument to indicate
            # the mode of bn layer. Note that when sampling images
            # using trained model, you need to set train='False'.
            #######################################################
            s_h, s_w = self.output_size, self.output_size
            s_h2, s_h4 = int(s_h/2), int(s_h/4)
            s_w2, s_w4 = int(s_w/2), int(s_w/4)

            h0 = tf.nn.relu(batch_norm(linear(z, 1024, 'g_h0_lin'), name='g_bn0'))

            h1 = tf.nn.relu(batch_norm(linear(h0, 64*2*s_h4*s_w4, 'g_h1_lin'), name='g_bn1'))
            h1 = tf.reshape(h1, [self.batch_size, s_h4, s_w4, 64 * 2])

            h2 = tf.nn.relu(batch_norm(deconv2d(h1, [self.batch_size, s_h2, s_w2, 64 * 2], name='g_h2'), name='g_bn3'))

            self.x_fake = tf.nn.sigmoid(deconv2d(h2, [self.batch_size, s_h, s_w, self.c_dim], name='g_h3'))

            return self.x_fake
            #######################################################
            #                   end of your code
            #######################################################

    def build_model(self):
        #######################################################
        # TODO: In this build_model function, define inputs,
        # operations on inputs and loss of DCGAN. For input,
        # you need to define it as placeholders. Discriminator
        # loss has two parts: cross entropy for real images and
        # cross entropy for fake images generated by generator.
        # Set reuse=True for discriminator when calculating the
        # second cross entropy. Define two different loss terms
        # for discriminator and generator, and save them as
        # self.d_loss and self.g_loss respectively.
        #######################################################

        label_smoothing = 0.9

        # inputs
        self.z = tf.placeholder(tf.float32, shape=(self.batch_size, self.z_dim))
        self.x = tf.placeholder(tf.float32, shape=(self.batch_size, self.input_size, self.input_size, self.c_dim))

        g = self.generator(self.z)
        d_real, d_real_logits = self.discriminator(self.x)
        d_fake, d_fake_logits = self.discriminator(g, reuse=True)

        # g_loss
        self.g_loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(\
                      logits=d_fake_logits,
                      labels=tf.ones_like(d_fake) * label_smoothing))

        # d_loss
        d_loss_real = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(\
                      logits=d_real_logits,
                      labels=tf.ones_like(d_real) * label_smoothing))
        d_loss_fake = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(\
                      logits=d_fake_logits,
                      labels=tf.zeros_like(d_fake) * label_smoothing))
        self.d_loss = d_loss_real + d_loss_fake
        #######################################################
        #                   end of your code
        #######################################################
        # define var lists for generator and discriminator
        t_vars = tf.trainable_variables()

        self.d_vars = [var for var in t_vars if 'discriminator' in var.name]
        self.g_vars = [var for var in t_vars if 'generator' in var.name]

        self.saver = tf.train.Saver()

    def train(self, config):
        # create two optimizers for generator and discriminator,
        # and only update the corresponding variables.
        d_optim = tf.train.AdamOptimizer(config.learning_rate, beta1=config.beta1) \
            .minimize(self.d_loss, var_list=self.d_vars)
        g_optim = tf.train.AdamOptimizer(config.learning_rate, beta1=config.beta1) \
            .minimize(self.g_loss, var_list=self.g_vars)
        try:
            self.sess.run(tf.global_variables_initializer())
        except:
            tf.initialize_all_variables().run()

        # load MNIST data
        mnist = tf.contrib.learn.datasets.load_dataset("mnist")

        data = mnist.train.images
        data = data.astype(np.float32)
        data_len = data.shape[0]
        data = np.reshape(data, [-1, 28, 28, 1])
        data = data * 2.0 - 1.0

        counter = 1
        start_time = time.time()

        could_load, checkpoint_counter = self.load(self.checkpoint_dir)
        if could_load:
            counter = checkpoint_counter
            print(" [*] Load SUCCESS")
        else:
            print(" [!] Load failed...")

        for epoch in xrange(config.epoch):
            batch_idxs = min(data_len, config.train_size) // config.batch_size

            for idx in xrange(0, batch_idxs):
                batch_images = data[idx * config.batch_size:(idx + 1) * config.batch_size, :]
                #######################################################
                # TODO: Train your model here. Sample hidden z from
                # standard uniform distribution. In each step, run g_optim
                # twice to make sure that d_loss does not go to zero.
                # print the loss terms at each training step to monitor
                # the training process. Print sample images every
                # config.print_step steps.You may use function
                # save_images in utils.py to save images.
                #######################################################

                # batch_images = batch_images * 2
                batch_z = np.random.uniform(-1, 1, size=(self.batch_size, self.z_dim))
                
                self.sess.run(d_optim, feed_dict={self.x: batch_images, self.z: batch_z})
                self.sess.run(g_optim, feed_dict={self.x: batch_images, self.z: batch_z})

                train_loss_g = self.g_loss.eval({self.z: batch_z})
                if np.mod(counter, 10) == 1:
                    train_loss_d = self.d_loss.eval({self.z: batch_z, self.x: batch_images})
                    print("Epoch: [%2d] [%4d/%4d] time: %4.4f, d_loss: %.8f, g_loss: %.8f" \
                      % (epoch, idx, batch_idxs,
                        time.time() - start_time, train_loss_d, train_loss_g))
                #######################################################
                #                   end of your code
                #######################################################

                counter += 1
                if np.mod(counter, 550) == 1:
                    self.save(config.checkpoint_dir, counter)

                if np.mod(counter, 100) == 1:
                    samples = self.x_fake.eval({self.z: batch_z})
                    save_images(samples, image_manifold_size(samples.shape[0]),
                          './{}/train_{:02d}_{:04d}.png'.format(config.sample_dir, epoch, idx+1))
                    print("[Sample] d_loss: %.8f, g_loss: %.8f" % (train_loss_d, train_loss_g)) 

    @property
    def model_dir(self):
        return "{}_{}_{}_{}".format(
            self.dataset_name, self.batch_size,
            self.output_size, self.output_size)

    def save(self, checkpoint_dir, step):
        model_name = "DCGAN.model"
        checkpoint_dir = os.path.join(checkpoint_dir, self.model_dir)

        if not os.path.exists(checkpoint_dir):
            os.makedirs(checkpoint_dir)

        self.saver.save(self.sess,
                        os.path.join(checkpoint_dir, model_name),
                        global_step=step)

    def load(self, checkpoint_dir):
        import re
        print(" [*] Reading checkpoints...")
        checkpoint_dir = os.path.join(checkpoint_dir, self.model_dir)

        ckpt = tf.train.get_checkpoint_state(checkpoint_dir)
        if ckpt and ckpt.model_checkpoint_path:
            ckpt_name = os.path.basename(ckpt.model_checkpoint_path)
            self.saver.restore(self.sess, os.path.join(checkpoint_dir, ckpt_name))
            counter = int(next(re.finditer("(\d+)(?!.*\d)", ckpt_name)).group(0))
            print(" [*] Success to read {}".format(ckpt_name))
            return True, counter
        else:
            print(" [*] Failed to find a checkpoint")
            return False, 0
